[package]
name = "rust-bootloader"
version = "0.1.0"
edition = "2024"

[dependencies]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
default = ["qemu"]
qemu = []
bbb = []

# use qemu when doing cargo run
[package.metadata.default-run]
features = ["qemu"]
